version: '2'
services:
  nginx:
    build:
      context: ./nginx
    image: reactjs_nginx
    container_name: reactjs_nginx_container
    ports:
      - "80:8080"
    volumes:
      - ./app/dist:/wwwroot:ro